### ISSUE TITLE
Broken link to system architecture in local_setup.md

### ISSUE THREAD

**Issue by roberthbailey** [gardener/node-controller-manager#4]
On https://github.com/gardener/node-controller-manager/blob/master/docs/development/local_setup.md the link to "architecture of the Node Controller Manager" is broken and returns a 404. I think it's probably meant to point to https://github.com/gardener/node-controller-manager/blob/master/docs/design/README.md.

**Comment by hardikdr** [comment]
Thanks for informing, I have fixed the broken-link.

**Comment by msohn** [comment]
verified that link was fixed
