### ISSUE TITLE
Drain Machines while scaling down

### ISSUE THREAD

**Issue by hardikdr** [gardener/node-controller-manager#9]
We should drain the Machines before we scale them down via MachineSet. Interesting question would be, which controller should we give responsibility of draining. 
Possible options could be : MachienSet or introduce new drain-controller. 

On the same line, we should also add new value for MachinePhase, DRAINING(?) may be.

**Comment by rfranzke** [comment]
What would be nice as well would be a "force-delete" mode where the drain/cordon steps would be skipped. This is particular interesting when deleting a cluster where you do not want to wait until all machines have been drained.
However, I'm not sure what's the best way to trigger that...

**Comment by prashanth26** [comment]
I have implemented the drain logic, but I am still not sure about the best way to trigger forced deletion.

**Comment by rfranzke** [comment]
Can this issue be closed?

**Comment by hardikdr** [comment]
Yes sure, this has been implemented now.
